# Generated by Django 5.0.6 on 2024-05-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
