# Generated by Django 5.0.6 on 2024-05-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
